<a href="https://colab.research.google.com/github/rocket0l4/ML-files/blob/main/linerar_regression_with_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
class NiYaar:
  def __init__(self):
      self.m = None
      self.b = None

  def fit(self,X_train,y_train):
      # print(X_train.shape)
      num = 0
      den = 0

      for i in range(X_train.shape[0]):
        num += (X_train[i] - X_train.mean()) * (y_train[i] -y_train.mean())
        den  += (X_train[i] - X_train.mean())*(X_train[i] - X_train.mean())

      self.m = num/den
      self.b = y_train.mean() - (self.m * X_train.mean())
      print(self.m)
      print(self.b)


  def predict(self,X_test):
      return self.m * X_test +self.b

In [2]:
import numpy as np
import pandas as pd


In [24]:
df = pd.read_csv('/content/drive/MyDrive/Salary.csv')
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [25]:
df.notnull().sum()

YearsExperience    35
Salary             35
dtype: int64

In [26]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [27]:
X

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5, 11.2, 11.5, 12.3,
       12.9, 13.5])

In [28]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872, 127345, 126756,
       128765, 135675, 139465])

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [30]:
X_train.shape

(28,)

In [31]:
lr = NiYaar()

In [32]:
lr.fit(X_train,y_train)

8672.22499845539
29821.64134895608


In [33]:
lr.predict(X_test[0])

65377.76384262317

In [34]:
X_test[0]

4.1

In [35]:
X_test

array([ 4.1,  4.5,  9.5,  3.7, 10.3, 12.3,  1.1])

In [36]:
y_test

array([ 57081,  61111, 116969,  57189, 122391, 128765,  39343])

In [37]:
X_train.mean()

6.260714285714286