<a href="https://colab.research.google.com/github/rocket0l4/ML-files/blob/main/Multiple_linear_Regression_by_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from sklearn.datasets import load_diabetes

In [12]:
X,y = load_diabetes(return_X_y=True)

In [13]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [14]:
X.shape

(442, 10)

In [15]:
y.shape

(442,)

#Using Sklearn's Linear Regression

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [18]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
reg  = LinearRegression()

In [21]:
reg.fit(X_train,y_train)

LinearRegression()

In [22]:
y_pred = reg.predict(X_test)

In [23]:
from sklearn.metrics import r2_score

In [24]:
r2_score(y_test,y_pred)

0.4399338661568968

In [25]:
reg.coef_ # Slope values Beta-1 to Beta-10

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [26]:
reg.intercept_ # Beta not

151.88331005254167

#Making my own Linear regression

In [30]:
class MeraLR:

  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis=1)

    # Use X_train.T to get the transpose of X_train
    beta = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = beta[0]
    self.coef_ = beta[1:]

  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coef_)+self.intercept_
    return y_pred

In [31]:
lr = MeraLR()

In [32]:
lr.fit(X_train,y_train)

In [33]:
y_pred = lr .predict(X_test)

In [34]:
r2_score(y_test,y_pred)

0.43993386615689634

In [35]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [36]:
lr.intercept_

151.88331005254165